name: vax-github-actions

on:
  schedule:
    - cron: "0 8,13,19,21,23 * * *"

jobs:
  update-vax-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          ref: main
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create folder and run script
        run: |
          mkdir -p data
          python get_vax_data.py data/
      - name: Commit changes
        run: |
            git config --global user.name 'Salvatore Larosa'
            git config --global user.email 'slarosa@users.noreply.github.com'
            git add -A
            git diff-index --quiet HEAD || git commit -am "Update VAX data on `date +'%Y-%m-%d %H:%M:%S'`"
            git push
